### PR TITLE
Rating & Snackbar/Toast/Notify 

### PR DESCRIPTION
**Pull request by kirti2602**
Feat: - Ratings and Snackbar/Toast/Notify components created inside this branch

### CODE REVIEW

**Review by harshitpaliwal95 — CHANGES_REQUESTED** [review]
snackbar position should be fixed in bottom of the page
Screenshot 2022-02-06 at 11 51 19 PM

**Comment by harshitpaliwal95** [comment]
overall looks good 👍🏻

**Review by vikrantkode — COMMENTED** [review]
Overall looks good to me. You can merge it

**Comment by kirti2602** [comment]
> overall looks good 👍🏻



> snackbar position should be fixed in bottom of the page Screenshot 2022-02-06 at 11 51 19 PM
Sure I'll place it at the bottom of screen

**Pull request merged**
