### PR TITLE
Alert & button components 

### PR DESCRIPTION
**Pull request by kirti2602**
Feat. - i) Alert component with 3 variants
           ii) Button component with 6 variants

### CODE REVIEW

**Review by Asuraking1n — COMMENTED** [review]
Looks good to me...
Just not responsive for moble

**Review by sakshi006 — COMMENTED** [review]
Looks good.

**Comment by kirti2602** [comment]
> Looks good to me... Just not responsive for moble

Thanks for the feedback. I'll redo responsiveness

**Comment by kirti2602** [comment]
> Looks good.

Thanks for reviewing

**Pull request merged**
